""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Configuration
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" No useless compatability with vi
set nocompatible

" Always use unicode
scriptencoding utf-8
set encoding=utf-8
set fileformat=unix

" Enable syntax highlighting
syntax on
" Required by vundle
filetype off
" Set color scheme
colorscheme elflord

" Ruby community standart indentation
set autoindent
set expandtab
set shiftwidth=2
set softtabstop=2

" Show extra whitespace
set list listchars=tab:>-

" Show line numbers
set number

" History
set history=5000

" Vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" Enable file-type specific plugins
filetype plugin on
" Enable file-type specific indenting
filetype indent on

Bundle 'tpope/vim-sensible'
Bundle 'vim-ruby/vim-ruby'
Bundle 'noahfrederick/vim-skeleton'
Bundle 'itchyny/calendar.vim'
Bundle 'scrooloose/nerdcommenter'
Bundle 'wellbredgrapefruit/tomdoc.vim'

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Key bindings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" F2 saves a file if necessary
nmap <F2> :update<CR>
vmap <F2> <Esc><F2>gv
imap <F2> <c-o><F2>
" F5 to insert current date
:inoremap <F5> <C-R>=strftime("%F")<CR>

" Remove trailing whitespaces
nnoremap <Leader>rtw :%s/\s\+$//e<CR>

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Commands
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Execute current file
nmap <F10> :!%:p<CR>

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Misc
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Highlight trailing whitespaces
match ErrorMsg '\s\+$'

" Leave insert mode on idle
au CursorHoldI * stopinsert
"au InsertEnter * let updaterestore=&updatetime | set updatetime=10000
"au InsertEnter * let &updatetime=updaterestore

highlight Normal guibg=#32322f ctermbg=236
highlight NonText guibg=#32322f ctermbg=236
highlight ColorColumn guibg=#000000 ctermbg=0
highlight Search ctermbg=cyan ctermfg=black
" it was 2015 year, the year of fire... the year of destruction
let &colorcolumn=join(range(81,999),",")
let &colorcolumn="80,".join(range(133,999),",")

" Add/change file extension in current buffer
" http://vim.wikia.com/wiki/Add/change_file_extension_in_current_buffer
command! -nargs=1 AddExt execute "saveas ".expand("%:p").<q-args>
command! -nargs=1 ChgExt execute "saveas ".expand("%:p:r").<q-args>

" Automatically create directories on save
function s:MkNonExDir(file, buf)
  if empty(getbufvar(a:buf, '&buftype')) && a:file!~#'\v^\w+\:\/'
    let dir=fnamemodify(a:file, ':h')
    if !isdirectory(dir)
      call mkdir(dir, 'p')
    endif
  endif
endfunction

augroup BWCCreateDir
  autocmd!
  autocmd BufWritePre * :call s:MkNonExDir(expand('<afile>'), +expand('<abuf>'))
augroup END

function! Min(number, ...)
  let result = a:number
  let index = a:0
  while index > 0
    let result = (a:{index} > result) ? result : a:{index}
    let index = index - 1
  endwhile
  return result
endf
