#!/usr/bin/env zsh

setopt APPEND_HISTORY      # Append history list to the history file
setopt AUTO_CD             # Perform cd to the command if it can't be executed
setopt HIST_IGNORE_DUPS    # Do not enter duplicate command lines into the history list
setopt HIST_IGNORE_SPACE   # Remove command lines from the history list when the first character on the line is a space
setopt INTERACTIVECOMMENTS # Allow comments even in interactive shells
setopt NOCLOBBER           # Do not allows  '>'  redirection  to  truncate  existing files, and '>>' to create files
setopt NOTIFY              # Report the status of background jobs immediately
setopt PROMPT_SUBST        # Enable parameter expansion, command substitution and arithmetic expansion in prompt
setopt SHARE_HISTORY       # Import new commands from the history file, and causes typed commands to be appended to the history file

# Prompt
autoload -U promptinit
promptinit
prompt clint

# Completion
autoload -Uz compinit
compinit

# Make sure that the terminal is in application mode when zle is active, since
# only then values from $terminfo are valid
if (( ${+terminfo[smkx]} )) && (( ${+terminfo[rmkx]} )); then
  function zle-line-init() {
    echoti smkx
  }
  function zle-line-finish() {
    echoti rmkx
  }
  function zle-keymap-select {
    zle reset-prompt
  }
  zle -N zle-line-init
  zle -N zle-line-finish
  zle -N zle-keymap-select
fi

# Ensure that the prompt is redrawn when the terminal size changes.
TRAPWINCH() {
  zle && { zle reset-prompt; zle -R }
}

bindkey -e

bindkey '^P' up-history                               # [Ctrl-p]    - Move to the previous event in the history list
bindkey '^N' down-history                             # [Ctrl-n]    - Move to the next event in the history list
bindkey '^?' backward-delete-char                     # [Backspace] - Delete the character behind the cursor
bindkey '^h' backward-delete-char                     # [Ctrl-h]    - ″
bindkey '^w' backward-kill-word                       # [Ctrl-w]    - Kill the word behind the cursor
bindkey '\M-F' forward-word
bindkey '\M-B' backward-word
# Escape
bindkey '\ew' kill-region
bindkey -s '\e,ll' 'ls -lh\n'
bindkey -s '\e,-' 'cd -\n'
bindkey -s '\e,v' 'vim\n'
bindkey -s '\e,s' '^Rssh ' # rev search ssh

# Edit the current command line in $EDITOR
autoload -U edit-command-line
zle -N edit-command-line
bindkey '\C-x\C-e' edit-command-line

if [[ "${terminfo[kcuu1]}" != "" ]]; then
  bindkey "${terminfo[kcuu1]}" up-line-or-search      # start typing + [Up-Arrow] - fuzzy find history forward
fi
if [[ "${terminfo[kcud1]}" != "" ]]; then
  bindkey "${terminfo[kcud1]}" down-line-or-search    # start typing + [Down-Arrow] - fuzzy find history backward
fi

if [[ "${terminfo[khome]}" != "" ]]; then
  bindkey "${terminfo[khome]}" beginning-of-line      # [Home] - Go to beginning of line
fi
if [[ "${terminfo[kend]}" != "" ]]; then
  bindkey "${terminfo[kend]}"  end-of-line            # [End] - Go to end of line
fi

bindkey ' ' magic-space                               # [Space] - do history expansion

# if mode indicator wasn't setup by theme, define default
if [[ "$MODE_INDICATOR" == "" ]]; then
  MODE_INDICATOR="%{$fg_bold[red]%}<%{$fg[red]%}<<%{$reset_color%}"
fi

function vi_mode_prompt_info() {
  echo "${${KEYMAP/vicmd/$MODE_INDICATOR}/(main|viins)/}"
}

# define right prompt, if it wasn't defined by a theme
if [[ "$RPS1" == "" && "$RPROMPT" == "" ]]; then
  RPS1='$(vi_mode_prompt_info)'
fi

# The following lines were added by compinstall
zstyle :compinstall filename '/etc/zsh/zshrc'

if [[ "${UID}" -ge 1000 ]] && [[ $- == *i* ]]; then
  # gpg-agent
  envfile=${HOME}/.gnupg/gpg-agent.env
  if [[ -f "${envfile}" ]]; then
    GPG_TTY=$(tty)
    source "${envfile}"
    export GPG_AGENT_INFO
    export SSH_AUTH_SOCK
    export SSH_AGENT_PID
    export GPG_TTY
  fi

  autoload -U tetris
  zle -N tetris
  bindkey  tetris

  if [[ -z "$TMUX" ]]; then
    exec tmux new -A -s main
  fi
fi

[[ -f ~/dotfiles/zsh/env ]] \
  && source ~/dotfiles/zsh/env
[[ -f ~/dotfiles/zsh/aliases.zsh ]] \
  && source ~/dotfiles/zsh/aliases.zsh
[[ -f ~/dotfiles/zsh/functions.zsh ]] \
  && source ~/dotfiles/zsh/functions.zsh
[[ -s ~/dotfiles/qfc/bin/qfc.sh ]] \
  && source ~/dotfiles/qfc/bin/qfc.sh

# added by travis gem
[ -f /home/leat/.travis/travis.sh ] && source /home/leat/.travis/travis.sh
